/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SignupIndexRouteImport } from './routes/signup/index'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as LayoutConfigRouteImport } from './routes/_layout/config'
import { Route as ApiTrpcSplatRouteImport } from './routes/api.trpc.$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as LayoutManuaisDepartamentoRouteImport } from './routes/_layout/manuais/$departamento'
import { Route as LayoutDepartamentosDepartamentoSlugRouteImport } from './routes/_layout/departamentos/$departamentoSlug'

const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupIndexRoute = SignupIndexRouteImport.update({
  id: '/signup/',
  path: '/signup/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutConfigRoute = LayoutConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => LayoutRoute,
} as any)
const ApiTrpcSplatRoute = ApiTrpcSplatRouteImport.update({
  id: '/api/trpc/$',
  path: '/api/trpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutManuaisDepartamentoRoute =
  LayoutManuaisDepartamentoRouteImport.update({
    id: '/manuais/$departamento',
    path: '/manuais/$departamento',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutDepartamentosDepartamentoSlugRoute =
  LayoutDepartamentosDepartamentoSlugRouteImport.update({
    id: '/departamentos/$departamentoSlug',
    path: '/departamentos/$departamentoSlug',
    getParentRoute: () => LayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/config': typeof LayoutConfigRoute
  '/login': typeof LoginIndexRoute
  '/signup': typeof SignupIndexRoute
  '/departamentos/$departamentoSlug': typeof LayoutDepartamentosDepartamentoSlugRoute
  '/manuais/$departamento': typeof LayoutManuaisDepartamentoRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/config': typeof LayoutConfigRoute
  '/login': typeof LoginIndexRoute
  '/signup': typeof SignupIndexRoute
  '/departamentos/$departamentoSlug': typeof LayoutDepartamentosDepartamentoSlugRoute
  '/manuais/$departamento': typeof LayoutManuaisDepartamentoRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_layout': typeof LayoutRouteWithChildren
  '/_layout/config': typeof LayoutConfigRoute
  '/login/': typeof LoginIndexRoute
  '/signup/': typeof SignupIndexRoute
  '/_layout/departamentos/$departamentoSlug': typeof LayoutDepartamentosDepartamentoSlugRoute
  '/_layout/manuais/$departamento': typeof LayoutManuaisDepartamentoRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/config'
    | '/login'
    | '/signup'
    | '/departamentos/$departamentoSlug'
    | '/manuais/$departamento'
    | '/api/auth/$'
    | '/api/trpc/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/config'
    | '/login'
    | '/signup'
    | '/departamentos/$departamentoSlug'
    | '/manuais/$departamento'
    | '/api/auth/$'
    | '/api/trpc/$'
  id:
    | '__root__'
    | '/'
    | '/_layout'
    | '/_layout/config'
    | '/login/'
    | '/signup/'
    | '/_layout/departamentos/$departamentoSlug'
    | '/_layout/manuais/$departamento'
    | '/api/auth/$'
    | '/api/trpc/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginIndexRoute: typeof LoginIndexRoute
  SignupIndexRoute: typeof SignupIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiTrpcSplatRoute: typeof ApiTrpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup/': {
      id: '/signup/'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/config': {
      id: '/_layout/config'
      path: '/config'
      fullPath: '/config'
      preLoaderRoute: typeof LayoutConfigRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/api/trpc/$': {
      id: '/api/trpc/$'
      path: '/api/trpc/$'
      fullPath: '/api/trpc/$'
      preLoaderRoute: typeof ApiTrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/manuais/$departamento': {
      id: '/_layout/manuais/$departamento'
      path: '/manuais/$departamento'
      fullPath: '/manuais/$departamento'
      preLoaderRoute: typeof LayoutManuaisDepartamentoRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/departamentos/$departamentoSlug': {
      id: '/_layout/departamentos/$departamentoSlug'
      path: '/departamentos/$departamentoSlug'
      fullPath: '/departamentos/$departamentoSlug'
      preLoaderRoute: typeof LayoutDepartamentosDepartamentoSlugRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutConfigRoute: typeof LayoutConfigRoute
  LayoutDepartamentosDepartamentoSlugRoute: typeof LayoutDepartamentosDepartamentoSlugRoute
  LayoutManuaisDepartamentoRoute: typeof LayoutManuaisDepartamentoRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutConfigRoute: LayoutConfigRoute,
  LayoutDepartamentosDepartamentoSlugRoute:
    LayoutDepartamentosDepartamentoSlugRoute,
  LayoutManuaisDepartamentoRoute: LayoutManuaisDepartamentoRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LayoutRoute: LayoutRouteWithChildren,
  LoginIndexRoute: LoginIndexRoute,
  SignupIndexRoute: SignupIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiTrpcSplatRoute: ApiTrpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
